### ISSUE TITLE
[FR] Support plan metadata field `cost`

### ISSUE THREAD

**Issue by kanngiesser** [cloudfoundry/cloud-service-broker#1050]
**Is your feature request related to a problem? Please describe.**
The Open Service Broker API Specification describes [conventions for the opaque `plan metadata` field](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#plan-metadata-fields) on the [Service Plan Object](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-plan-object) which is returned from `/v2/catalog` requests. 

The Cloud-Service-Broker supports most of the fields which are described in the specification: It is possible to define values for `metdata.display_name` and `metadata.bullets` by adding the respective fields to the service definition yml (see [Brokerpak specification](https://github.com/cloudfoundry/cloud-service-broker/blob/main/docs/brokerpak-specification.md#plan-object)), but `metadata.cost` is missing. We require this information to make cost information available to our internal customers.

**Describe the solution you'd like**

It is possible to define cost information for the plan object (from yml service definition or environment variable `GSB_SERVICE_SERVICE_NAME_PLAN`):
```yml
plans:
  - name: standard
    id: dc939a71-d3d7-40d7-b9e7-9889d9270743
    display_name: standard
    description: standard plan
    free: false
    costs:
       - unit: Monthly
         amount: 
           EUR: 0.85
           USD: 1.00
```

Cost Metadata should is added to [Brokerpak Specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#plan-metadata-fields)

The Server returns cost information at the `v2/catalog` endpoint

**Describe alternatives you've considered**
--

**Additional Context**
--

**Priority**
Low

**Priority Context**

**Platform** 
AWS

**Applicable Services**
all services and plans
