### ISSUE TITLE
[FR] Provide hook for script to run when testing examples

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/cloud-service-broker#723]
**Is your feature request related to a problem? Please describe.**
When writing a brokerpak, we need to test attributes of the provisioned instance to demonstrate compliance, and sometimes also to test that provision/bind arguments were properly applied. 

@blgm added a new CSB feature to [spin up the CSB for the duration of `csb run-examples`](https://github.com/cloudfoundry/cloud-service-broker/pull/714). That's great, and removes a lot of developer donkey-work! However, it still leaves no affordance for testing attributes of the the provisioned instance.

**Describe the solution you'd like**
For each example in the service YAML, I want to specify a test script. When `csb run-examples` is invoked, it will call the specified test script between the provision+bind/unbind+deprovision steps.

**Describe alternatives you've considered**
We currently do this with a fairly elaborate Makefile: Understanding and maintaining the Makefile is a lot of friction to deal with a fairly simple requirement. There's a lot of scaffolding to stand up the CSB running the brokerpak, provision and bind an instance, then run the tests, then tear down the instance. It's finicky code, repetitive across repositories, and has a tendency to drift as people tinker with it. Also it's easy to forget to restart the CSB to pick up brokerpak changes between test runs. 

**Additional Context**
Example [Makefile](https://github.com/GSA-TTS/datagov-brokerpak-smtp/blob/main/Makefile) and [test script](https://github.com/GSA-TTS/datagov-brokerpak-smtp/blob/main/test.sh) (which verifies that DMARC and SPF are configured correctly) for a simple SMTP service. Note how the Makefile has to rely on a Docker image to do its thing. So in addition to brokerpak and Terraform knowhow, someone may have to know a lot about Docker and Makefiles to start working on brokerpak code... Definitely not ideal!

**Priority**
Low

**Priority Context**
We have the Makefile workaround, though we're not happy with it. If you prioritize it, it will make our lives easier because we can drop fairly opaque code that no one wants to understand. It may also draw more people to development of brokerpaks because it's so easy to incorporate tests into the development workflow.

**Platform** 
N/A

**Applicable Services**
All

**Comment by blgm** [comment]
Hi @mogul, this is a great idea.

Currently an example definition looks like:
```yaml
examples:
- name: An example
  description: Create a thing.
  plan_id: 3ba75688-ac57-11ed-9b25-fbc8396b95f4
  provision_params: {"memory_size_gb": 1}
  bind_params: {}
```

I was thinking that this could be extended to look something like:
```yaml
examples:
- name: An example
  description: Create a thing.
  plan_id: 3ba75688-ac57-11ed-9b25-fbc8396b95f4
  provision_params: {"memory_size_gb": 1}
  bind_params: {}
  validation:
    command: ./test-script.sh
```
Is that the sort of thing that you were thinking too?

I would imagine passing the binding credentials to the test script via STDIN, because it raises fewer security concerns than using a temporary file or passing JSON as a command line parameter.

One of the potential limitations of this approach would be networking. For example, when creating an RDS, it's quite common to put it in a subnet that does not have public access, so a validation script might not be able to connect. There are ways to work around that, but I just thought it was worth mentioning.

For quite a lot of the tests that I write, I create more than one binding. This is to make sure that what you write with one binding can be read by another. I was thinking that for examples testing, perhaps it would be sufficient to have just one binding. Do you have any thoughts about that?
