### ISSUE TITLE
[BUG] The flag instances_retrievable and bindings_retrievable is not available any more

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry/cloud-service-broker#754]
## Description
The flag instances_retrievable and bindings_retrievable is not available any more. 
https://github.com/cloudfoundry/cloud-service-broker/blob/ae28d2257d200216478f64b0d23f4750d2913912/pkg/broker/service_definition.go#L52

These flags must be present in case we have the fetch instance and the fetch binding available.

## Expected Behavior
The catalog must return these flags at true if they are set to true at the definition.yml level.

## Actual Behavior
Currently these flag are not present in the catalog even if they are set to true into the service definition.yml

## Context
This feature does effect the orange customer project as UI was implemented in a previous version but once migrated to a version > to 0.9 these information has been lost and we try currently to implement the fetch instance and the fetch binding on our side.

## Curent service definition.yml
```yaml
version: 1
name: IaaS-proxy
id: <id>
description: Forward proxy service 
display_name: proxy-cloud
tags: [internet,,proxy,]
plan_updateable: true
instances_retrievable: true
bindings_retrievable: true
plans:
- name: standard
  id: <id>

```

Thanks in avance.

Regards,
